stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - mkdir -p ~/.terminus/plugins
    - composer create-project -n -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:^1
  script:
    - echo "Running composer updates"
    - /home/ash/vendor/bin/terminus auth:login -n --email=sattleram@ornl.gov
    # The oldest multidev testing env is deleted
    - /home/ash/vendor/bin/terminus multidev:delete wwwornl.mdev --yes
    # Build step
    - composer build-assets
    - /home/ash/vendor/bin/terminus env:wake wwwornl.dev
    # Create new multidev
    - /home/ash/vendor/bin/terminus multidev:create wwwornl.dev mdev
    - /home/ash/vendor/bin/terminus drush wwwornl.mdev -- config-import --yes

deploy_dev:
  stage: deploy
  script:
    - echo "Deploy to dev server"
    # Build artifacts pushed up to dev environment
    - /home/ash/vendor/bin/terminus multidev:merge-to-dev wwwornl.mdev
    - /home/ash/vendor/bin/terminus drush wwwornl.dev -- config-import --yes
  environment:
    name: dev
    url: http://dev-wwwornl.pantheonsite.io/
  only:
    - dev

