stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Running composer updates"
    - php composer.phar update

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to dev server"
  environment:
    name: dev
    url: http://dev-wwwornl.pantheonsite.io/
  only:
  - master

