stages:
  - deploy

deploy_dev:
  stage: deploy
  script:
    - echo "Deploy to dev pantheon server"
    - terminus auth:login --sattleram@ornl.gov
    - terminus connection:set wwwornl.dev git
    - terminus upstream:updates:apply wwwornl
    - terminus connection:set wwwornl.dev sftp
    - terminus composer wwwornl.dev -- update
    - terminus env:commit wwwornl.dev --message="GitLab Dev Repo Push"
    - terminus drush config-import
    - terminus connection:set wwwornl.dev git
  environment:
    name: dev
    url: http://dev-wwwornl.pantheonsite.io/
  only:
    - dev
