stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  before_script:
    - terminus auth:login email=sattleram@ornl.gov
    - terminus composer wwwornl.dev -- update
  script: echo "Running composer updates"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to dev server"
  environment:
    name: dev
    url: http://dev-wwwornl.pantheonsite.io/
  only:
  - master

